name: Configure Azure Environment

# Controls when the workflow will run
on:
  # Triggers the workflow when labeled pull request events 
  pull_request:
    types: [labeled]

env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"North Europe"'
  AZURE_WEBAPP_NAME: pabloperfer-ttt-app

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-up-azure-resources: 
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.Azure_CREDENTIALS }}
          
      - name: Create Azure resource group
        if: success()
        run: |
          az group create -- location ${{env.AZURE_LOCATION}} --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
      
      - name: Create Azure app service plan
        if: success()
        run: |
          az appservice plan create --resource-group ${{env.AZURE_RESOURCE_GROUP}} --name ${{env.AZURE_APP_PLAN}} --is-linux sky F1 --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
          
